# Generated by Django 3.2.7 on 2021-09-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='ChoiceCustomer',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionCustomer',
        ),
    ]
